config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: 1.6.0-alpha5
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/eosc-synergy/sqaaas-api-server:
      branch: release/2.0.0
      repo: https://github.com/eosc-synergy/sqaaas-api-server
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/eosc-synergy/sqaaas-api-server git:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-scarlet-worm.sh
        container: qc.acc_wiggy-scarlet-tamarin
  QC.Doc:
    repos:
      github.com/eosc-synergy/sqaaas-api-server find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.gimpy-charcoal-ibis.sh
        container: qc.doc_beady-azure-dachshund
      github.com/eosc-synergy/sqaaas-api-server markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.shaggy-mustard-hippopotamus.sh
        container: qc.doc_skinny-harlequin-spaniel
  QC.Lic:
    repos:
      github.com/eosc-synergy/sqaaas-api-server licensee:
        commands:
        - /usr/bin/env sh .sqa/script.scaly-aqua-angelfish.sh
        container: qc.lic_frumpy-chestnut-blue
  QC.Sec:
    repos:
      github.com/eosc-synergy/sqaaas-api-server bandit:
        commands:
        - /usr/bin/env sh .sqa/script.frumpy-charcoal-quail.sh
        container: qc.sec_skinny-khaki-gar
  QC.Sty:
    repos:
      github.com/eosc-synergy/sqaaas-api-server flake8:
        commands:
        - /usr/bin/env sh .sqa/script.cloudy-chocolate-rat.sh
        container: qc.sty_nippy-linen-fousek
  QC.Ver:
    repos:
      github.com/eosc-synergy/sqaaas-api-server is_semver.py:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-salmon-fly.sh
        container: qc.ver_surly-dandelion-rottweiler
timeout: 600
