config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: 1.6.0-alpha5
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/eosc-synergy/sqaaas-api-server:
      branch: master
      repo: https://github.com/eosc-synergy/sqaaas-api-server
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/eosc-synergy/sqaaas-api-server git:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-ecru-chin.sh
        container: qc.acc_greasy-scarlet-lobster
  QC.Doc:
    repos:
      github.com/eosc-synergy/sqaaas-api-server find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.smelly-lilac-pig.sh
        container: qc.doc_homely-scarlet-cockroach
      github.com/eosc-synergy/sqaaas-api-server markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.homely-gamboge-cockroach.sh
        container: qc.doc_queasy-buff-ladybird
  QC.Lic:
    repos:
      github.com/eosc-synergy/sqaaas-api-server licensee:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-cerise-fossa.sh
        container: qc.lic_sloppy-turquoise-orangutan
  QC.Sec:
    repos:
      github.com/eosc-synergy/sqaaas-api-server bandit:
        commands:
        - /usr/bin/env sh .sqa/script.woolly-apricot-pinscher.sh
        container: qc.sec_silly-ruby-gerbil
  QC.Sty:
    repos:
      github.com/eosc-synergy/sqaaas-api-server flake8:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-magnolia-meerkat.sh
        container: qc.sty_homey-yellow-seal
  QC.Ver:
    repos:
      github.com/eosc-synergy/sqaaas-api-server is_semver.py:
        commands:
        - /usr/bin/env sh .sqa/script.queasy-auburn-flamingo.sh
        container: qc.ver_hasty-ivory-reindeer
timeout: 600
