config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: 1.6.0-alpha5
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/eosc-synergy/sqaaas-api-server:
      branch: release/2.0.0
      repo: https://github.com/eosc-synergy/sqaaas-api-server
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/eosc-synergy/sqaaas-api-server git:
        commands:
        - /usr/bin/env sh .sqa/script.scummy-olive-javanese.sh
        container: qc.acc_cloudy-carmine-turtle
  QC.Doc:
    repos:
      github.com/eosc-synergy/sqaaas-api-server find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.tasty-puce-cockroach.sh
        container: qc.doc_queasy-chocolate-binturong
      github.com/eosc-synergy/sqaaas-api-server markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.blurry-rose-barb.sh
        container: qc.doc_gimpy-olive-tortoise
  QC.Lic:
    repos:
      github.com/eosc-synergy/sqaaas-api-server licensee:
        commands:
        - /usr/bin/env sh .sqa/script.craggy-lemon-oriole.sh
        container: qc.lic_cloudy-lavender-deer
  QC.Sec:
    repos:
      github.com/eosc-synergy/sqaaas-api-server bandit:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-beige-javanese.sh
        container: qc.sec_ugly-cornflower-clam
  QC.Sty:
    repos:
      github.com/eosc-synergy/sqaaas-api-server flake8:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-lilac-macaw.sh
        container: qc.sty_craggy-cobalt-hedgehog
  QC.Ver:
    repos:
      github.com/eosc-synergy/sqaaas-api-server is_semver.py:
        commands:
        - /usr/bin/env sh .sqa/script.crappy-scarlet-stingray.sh
        container: qc.ver_pretty-mustard-tang
timeout: 600
