config:
  credentials:
  - id: upv_im_id
    password_var: IM_PASS
    username_var: IM_USER
  - id: incd_openstack_id
    password_var: OPENSTACK_PASS
    username_var: OPENSTACK_USER
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: 1.7.0-alpha2
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/eosc-synergy/sqaaas-api-server:
      branch: master
      repo: https://github.com/eosc-synergy/sqaaas-api-server
    github.com/eosc-synergy/sqaaas-docs:
      branch: master
      repo: https://github.com/eosc-synergy/sqaaas-docs
    github.com/orviz/IM-sqaaas-test:
      branch: master
      repo: https://github.com/orviz/IM-sqaaas-test
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/eosc-synergy/sqaaas-api-server git:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-salmon-uguisu.sh
        container: qc.acc_ugly-platinum-fousek
  QC.Doc:
    repos:
      github.com/eosc-synergy/sqaaas-docs find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.tacky-peach-cougar.sh
        container: qc.doc_stinky-saffron-setter
      github.com/eosc-synergy/sqaaas-docs git:
        commands:
        - /usr/bin/env sh .sqa/script.tasty-purple-bullfrog.sh
        container: qc.doc_tacky-heliotrope-tuatara
      github.com/eosc-synergy/sqaaas-docs markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.goopy-goldenrod-bison.sh
        container: qc.doc_stuffy-vermilion-squirrel
  QC.FAIR:
    repos:
      github.com/eosc-synergy/sqaaas-api-server F-UJI:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-lemon-wallaby.sh
        container: qc.fair_muzzy-firebrick-koala
  QC.Lic:
    repos:
      github.com/eosc-synergy/sqaaas-api-server licensee:
        commands:
        - /usr/bin/env sh .sqa/script.baggy-khaki-penguin.sh
        container: qc.lic_snazzy-wheat-leopard
  QC.Sec:
    repos:
      github.com/eosc-synergy/sqaaas-api-server bandit:
        commands:
        - /usr/bin/env sh .sqa/script.cheeky-ochre-abyssinian.sh
        container: qc.sec_ugly-zucchini-frog
  QC.Sty:
    repos:
      github.com/eosc-synergy/sqaaas-api-server flake8:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-aquamarine-snake.sh
        container: qc.sty_lovely-lavender-dalmatian
  QC.Ver:
    repos:
      github.com/eosc-synergy/sqaaas-api-server get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.queasy-cyan-vulture.sh
        container: qc.ver_flaky-chocolate-chinchilla
  SvcQC.Dep:
    repos:
      github.com/orviz/IM-sqaaas-test im_client:
        commands:
        - /usr/bin/env sh .sqa/script.scanty-white-squirrel.sh
        container: svcqc.dep_tacky-ultramarine-rabbit
timeout: 600
