config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/gosec
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/eosc-synergy/sqaaas-api-server:
      branch: master
      repo: https://github.com/eosc-synergy/sqaaas-api-server
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/eosc-synergy/sqaaas-api-server git:
        commands:
        - /usr/bin/env sh .sqa/script.shaggy-apricot-moorhen.sh
        container: qc.acc_crappy-asparagus-badger
  QC.Doc:
    repos:
      github.com/eosc-synergy/sqaaas-api-server find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.cranky-lavender-burmese.sh
        container: qc.doc_slimy-red-hare
      github.com/eosc-synergy/sqaaas-api-server git:
        commands:
        - /usr/bin/env sh .sqa/script.chummy-cobalt-shark.sh
        container: qc.doc_cranky-orchid-guppy
      github.com/eosc-synergy/sqaaas-api-server markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.bluesy-saffron-badger.sh
        container: qc.doc_foggy-lemon-dugong
  QC.Lic:
    repos:
      github.com/eosc-synergy/sqaaas-api-server licensee:
        commands:
        - /usr/bin/env sh .sqa/script.sleepy-saffron-drever.sh
        container: qc.lic_skinny-alizarin-baboon
  QC.Sec:
    repos:
      github.com/eosc-synergy/sqaaas-api-server bandit:
        commands:
        - /usr/bin/env sh .sqa/script.skimpy-ochre-dingo.sh
        container: qc.sec_cheeky-linen-bear
      github.com/eosc-synergy/sqaaas-api-server gosec:
        commands:
        - /usr/bin/env sh .sqa/script.shabby-vermilion-owl.sh
        container: qc.sec_sickly-cinnamon-flounder
  QC.Sty:
    repos:
      github.com/eosc-synergy/sqaaas-api-server flake8:
        commands:
        - /usr/bin/env sh .sqa/script.blurry-orange-seahorse.sh
        container: qc.sty_stinky-aquamarine-lemming
  QC.Ver:
    repos:
      github.com/eosc-synergy/sqaaas-api-server get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-silver-angelfish.sh
        container: qc.ver_shaggy-azure-lynx
timeout: 1800
