config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: 1.6.0-alpha1
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/eosc-synergy/sqaaas-api-server:
      branch: master
      repo: https://github.com/eosc-synergy/sqaaas-api-server
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/eosc-synergy/sqaaas-api-server git:
        commands:
        - /usr/bin/env sh .sqa/script.scaly-rose-burmese.sh
        container: qc.acc_goopy-turquoise-chow
  QC.Doc:
    repos:
      github.com/eosc-synergy/sqaaas-api-server find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.thirsty-grey-elephant.sh
        container: qc.doc_stinky-rust-chipmunk
      github.com/eosc-synergy/sqaaas-api-server markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.pokey-amaranth-hornet.sh
        container: qc.doc_skanky-chestnut-oyster
  QC.FAIR:
    repos:
      github.com/eosc-synergy/sqaaas-api-server fair-eva:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-sapphire-gibbon.sh
        container: qc.fair_skanky-grey-serval
  QC.Lic:
    repos:
      github.com/eosc-synergy/sqaaas-api-server licensee:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-russet-collie.sh
        container: qc.lic_breezy-salmon-earwig
  QC.Sec:
    repos:
      github.com/eosc-synergy/sqaaas-api-server bandit:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-sepia-tortoise.sh
        container: qc.sec_baggy-ecru-labradoodle
  QC.Sty:
    repos:
      github.com/eosc-synergy/sqaaas-api-server flake8:
        commands:
        - /usr/bin/env sh .sqa/script.gamy-ecru-chihuahua.sh
        container: qc.sty_scaly-myrtle-tang
timeout: 600
