config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.7
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/eosc-synergy/sqaaas-api-server:
      branch: master
      repo: https://github.com/eosc-synergy/sqaaas-api-server
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/eosc-synergy/sqaaas-api-server git:
        commands:
        - /usr/bin/env sh .sqa/script.pokey-orchid-camel.sh
        container: qc.acc_slimy-vermilion-gharial
  QC.Doc:
    repos:
      github.com/eosc-synergy/sqaaas-api-server find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-dandelion-greyhound.sh
        container: qc.doc_scanty-magenta-bandicoot
      github.com/eosc-synergy/sqaaas-api-server git:
        commands:
        - /usr/bin/env sh .sqa/script.shabby-charcoal-argentino.sh
        container: qc.doc_nerdy-fuchsia-jackal
      github.com/eosc-synergy/sqaaas-api-server markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.leaky-carmine-sloth.sh
        container: qc.doc_messy-lemon-ladybird
  QC.Lic:
    repos:
      github.com/eosc-synergy/sqaaas-api-server licensee:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-olivine-shrimp.sh
        container: qc.lic_zippy-blue-quoll
  QC.Sec:
    repos:
      github.com/eosc-synergy/sqaaas-api-server bandit:
        commands:
        - /usr/bin/env sh .sqa/script.tasty-crimson-moth.sh
        container: qc.sec_blurry-wisteria-okapi
  QC.Sty:
    repos:
      github.com/eosc-synergy/sqaaas-api-server flake8:
        commands:
        - /usr/bin/env sh .sqa/script.leaky-chestnut-chow.sh
        container: qc.sty_gummy-chartreuse-walrus
      github.com/eosc-synergy/sqaaas-api-server hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.pokey-yellow-quail.sh
        container: qc.sty_silly-yellow-barnacle
      github.com/eosc-synergy/sqaaas-api-server jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-corn-forest.sh
        container: qc.sty_shaky-black-malamute
  QC.Ver:
    repos:
      github.com/eosc-synergy/sqaaas-api-server get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-cinnamon-emu.sh
        container: qc.ver_frumpy-tangerine-quail
timeout: 1800
