config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-api-server:
      branch: feature/contribution_files
      repo: https://github.com/EOSC-synergy/sqaaas-api-server
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: 1.7.0-only_im_client
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/EOSC-synergy/sqaaas-api-server git:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-chocolate-warthog.sh
        container: qc.acc_crabby-aqua-harrier
  QC.Doc:
    repos:
      github.com/EOSC-synergy/sqaaas-api-server find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.queasy-green-civet.sh
        container: qc.doc_squeaky-emerald-gar
      github.com/EOSC-synergy/sqaaas-api-server git:
        commands:
        - /usr/bin/env sh .sqa/script.shabby-zucchini-molly.sh
        container: qc.doc_lousy-zucchini-hare
      github.com/EOSC-synergy/sqaaas-api-server markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.shabby-asparagus-gerbil.sh
        container: qc.doc_squeaky-ochre-fox
  QC.FAIR:
    repos:
      github.com/EOSC-synergy/sqaaas-api-server F-UJI:
        commands:
        - /usr/bin/env sh .sqa/script.woolly-peach-serval.sh
        container: qc.fair_slimy-ruby-chow
  QC.Lic:
    repos:
      github.com/EOSC-synergy/sqaaas-api-server licensee:
        commands:
        - /usr/bin/env sh .sqa/script.cozy-rose-cockroach.sh
        container: qc.lic_ugly-black-woodpecker
  QC.Sec:
    repos:
      github.com/EOSC-synergy/sqaaas-api-server bandit:
        commands:
        - /usr/bin/env sh .sqa/script.frumpy-amaranth-jackal.sh
        container: qc.sec_muzzy-flax-hedgehog
  QC.Sty:
    repos:
      github.com/EOSC-synergy/sqaaas-api-server flake8:
        commands:
        - /usr/bin/env sh .sqa/script.thirsty-taupe-avocet.sh
        container: qc.sty_baggy-wisteria-yak
  QC.Ver:
    repos:
      github.com/EOSC-synergy/sqaaas-api-server get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.surly-myrtle-dolphin.sh
        container: qc.ver_woolly-sepia-gopher
timeout: 1800
