config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.5
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/eosc-synergy/sqaaas-api-server:
      branch: !!python/tuple
      - master
      - 23727cacc3e4f1a6f200727f3a9f7a1b2dcc5d5e
      repo: https://github.com/eosc-synergy/sqaaas-api-server
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/eosc-synergy/sqaaas-api-server git:
        commands:
        - /usr/bin/env sh .sqa/script.flaky-ultramarine-moose.sh
        container: qc.acc_gimpy-copper-frog
  QC.Doc:
    repos:
      github.com/eosc-synergy/sqaaas-api-server find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.scanty-cerise-tzu.sh
        container: qc.doc_homey-buff-shrimp
      github.com/eosc-synergy/sqaaas-api-server git:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-ecru-civet.sh
        container: qc.doc_woozy-gamboge-jaguar
      github.com/eosc-synergy/sqaaas-api-server markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.jumpy-lemon-woodpecker.sh
        container: qc.doc_bluesy-aquamarine-anteater
  QC.Lic:
    repos:
      github.com/eosc-synergy/sqaaas-api-server licensee:
        commands:
        - /usr/bin/env sh .sqa/script.smelly-lavender-okapi.sh
        container: qc.lic_nerdy-fuchsia-toucan
  QC.Sec:
    repos:
      github.com/eosc-synergy/sqaaas-api-server bandit:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-flax-booby.sh
        container: qc.sec_chewy-salmon-terrier
  QC.Sty:
    repos:
      github.com/eosc-synergy/sqaaas-api-server flake8:
        commands:
        - /usr/bin/env sh .sqa/script.flaky-crimson-whippet.sh
        container: qc.sty_gloppy-orange-caracal
      github.com/eosc-synergy/sqaaas-api-server hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.cheeky-pear-devil.sh
        container: qc.sty_shabby-buff-newfoundland
      github.com/eosc-synergy/sqaaas-api-server jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.zippy-wheat-insect.sh
        container: qc.sty_wimpy-auburn-chicken
  QC.Ver:
    repos:
      github.com/eosc-synergy/sqaaas-api-server get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-copper-insect.sh
        container: qc.ver_gimpy-bronze-chipmunk
timeout: 5400
