config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.5
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/eosc-synergy/sqaaas-api-server:
      branch: !!python/tuple
      - master
      - 23727cacc3e4f1a6f200727f3a9f7a1b2dcc5d5e
      repo: https://github.com/eosc-synergy/sqaaas-api-server
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/eosc-synergy/sqaaas-api-server git:
        commands:
        - /usr/bin/env sh .sqa/script.trippy-purple-tortoise.sh
        container: qc.acc_blurry-asparagus-barnacle
  QC.Doc:
    repos:
      github.com/eosc-synergy/sqaaas-api-server find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.homey-jade-gecko.sh
        container: qc.doc_freaky-turquoise-termite
      github.com/eosc-synergy/sqaaas-api-server git:
        commands:
        - /usr/bin/env sh .sqa/script.homely-wheat-toucan.sh
        container: qc.doc_trippy-eggplant-goose
      github.com/eosc-synergy/sqaaas-api-server markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.whiny-yellow-angora.sh
        container: qc.doc_sickly-purple-cuttlefish
  QC.Lic:
    repos:
      github.com/eosc-synergy/sqaaas-api-server licensee:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-salmon-penguin.sh
        container: qc.lic_pasty-thistle-lizard
  QC.Sec:
    repos:
      github.com/eosc-synergy/sqaaas-api-server bandit:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-tan-echidna.sh
        container: qc.sec_beady-linen-giraffe
  QC.Sty:
    repos:
      github.com/eosc-synergy/sqaaas-api-server flake8:
        commands:
        - /usr/bin/env sh .sqa/script.pokey-bronze-hornet.sh
        container: qc.sty_sunny-denim-seal
      github.com/eosc-synergy/sqaaas-api-server hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.messy-peach-tortoise.sh
        container: qc.sty_bluesy-blue-hyena
      github.com/eosc-synergy/sqaaas-api-server jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.tacky-wisteria-frise.sh
        container: qc.sty_geeky-dandelion-birman
  QC.Ver:
    repos:
      github.com/eosc-synergy/sqaaas-api-server get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.whiny-russet-akita.sh
        container: qc.ver_shaggy-green-fowl
timeout: 5400
