config:
  credentials:
  - id: upv_im_id
    password_var: IM_PASS
    username_var: IM_USER
  - id: incd_openstack_id
    password_var: OPENSTACK_PASS
    username_var: OPENSTACK_USER
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: 1.7.0-alpha1
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/eosc-synergy/sqaaas-api-server:
      branch: master
      repo: https://github.com/eosc-synergy/sqaaas-api-server
    github.com/eosc-synergy/sqaaas-docs:
      branch: master
      repo: https://github.com/eosc-synergy/sqaaas-docs
    github.com/orviz/IM-sqaaas-test:
      branch: master
      repo: https://github.com/orviz/IM-sqaaas-test
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/eosc-synergy/sqaaas-api-server git:
        commands:
        - /usr/bin/env sh .sqa/script.bluesy-peach-angelfish.sh
        container: qc.acc_slaphappy-jade-zorse
  QC.Doc:
    repos:
      github.com/eosc-synergy/sqaaas-docs find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-aqua-dachshund.sh
        container: qc.doc_cloudy-cyan-echidna
      github.com/eosc-synergy/sqaaas-docs git:
        commands:
        - /usr/bin/env sh .sqa/script.whiny-crimson-insect.sh
        container: qc.doc_skanky-mustard-husky
      github.com/eosc-synergy/sqaaas-docs markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-magnolia-newfoundland.sh
        container: qc.doc_sloppy-brown-clam
  QC.FAIR:
    repos:
      github.com/eosc-synergy/sqaaas-api-server F-UJI:
        commands:
        - /usr/bin/env sh .sqa/script.smelly-cerise-binturong.sh
        container: qc.fair_crappy-saffron-monkey
  QC.Lic:
    repos:
      github.com/eosc-synergy/sqaaas-api-server licensee:
        commands:
        - /usr/bin/env sh .sqa/script.cranky-coral-panda.sh
        container: qc.lic_stealthy-aqua-lynx
  QC.Sec:
    repos:
      github.com/eosc-synergy/sqaaas-api-server bandit:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-mauve-fousek.sh
        container: qc.sec_jumpy-harlequin-chow
  QC.Sty:
    repos:
      github.com/eosc-synergy/sqaaas-api-server flake8:
        commands:
        - /usr/bin/env sh .sqa/script.goopy-lavender-blue.sh
        container: qc.sty_messy-russet-shrew
  QC.Ver:
    repos:
      github.com/eosc-synergy/sqaaas-api-server get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-emerald-gharial.sh
        container: qc.ver_breezy-ruby-ragdoll
  SvcQC.Dep:
    repos:
      github.com/orviz/IM-sqaaas-test im_client:
        commands:
        - /usr/bin/env sh .sqa/script.zippy-ecru-bracke.sh
        container: svcqc.dep_flabby-cornflower-uguisu
timeout: 600
