config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.7
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/eosc-synergy/sqaaas-api-server:
      branch: master
      repo: https://github.com/eosc-synergy/sqaaas-api-server
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/eosc-synergy/sqaaas-api-server git:
        commands:
        - /usr/bin/env sh .sqa/script.ready-cyan-ferret.sh
        container: qc.acc_tasty-mustard-fish
  QC.Doc:
    repos:
      github.com/eosc-synergy/sqaaas-api-server find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.skanky-azure-seahorse.sh
        container: qc.doc_goopy-wisteria-guppy
      github.com/eosc-synergy/sqaaas-api-server git:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-olive-lobster.sh
        container: qc.doc_flimsy-celadon-civet
      github.com/eosc-synergy/sqaaas-api-server markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.gloppy-cinnabar-peccary.sh
        container: qc.doc_seedy-lilac-tamarin
  QC.Lic:
    repos:
      github.com/eosc-synergy/sqaaas-api-server licensee:
        commands:
        - /usr/bin/env sh .sqa/script.leaky-alizarin-butterfly.sh
        container: qc.lic_sloppy-sangria-discus
  QC.Met:
    repos:
      github.com/eosc-synergy/sqaaas-api-server cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.smelly-emerald-indri.sh
        container: qc.met_homely-sangria-paradise
  QC.Sec:
    repos:
      github.com/eosc-synergy/sqaaas-api-server bandit:
        commands:
        - /usr/bin/env sh .sqa/script.cheeky-aquamarine-cockroach.sh
        container: qc.sec_flaky-cornflower-frog
  QC.Sty:
    repos:
      github.com/eosc-synergy/sqaaas-api-server flake8:
        commands:
        - /usr/bin/env sh .sqa/script.bumpy-aqua-wombat.sh
        container: qc.sty_jumpy-emerald-armadillo
      github.com/eosc-synergy/sqaaas-api-server hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-jade-sparrow.sh
        container: qc.sty_hilly-viridian-loon
      github.com/eosc-synergy/sqaaas-api-server jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-celadon-frog.sh
        container: qc.sty_ugly-green-crane
  QC.Ver:
    repos:
      github.com/eosc-synergy/sqaaas-api-server get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-chartreuse-opossum.sh
        container: qc.ver_droopy-cerise-bird
timeout: 5400
