config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/eosc-synergy/sqaaas-api-server:
      branch: master
      repo: https://github.com/eosc-synergy/sqaaas-api-server
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/eosc-synergy/sqaaas-api-server git:
        commands:
        - /usr/bin/env sh .sqa/script.bumpy-auburn-grasshopper.sh
        container: qc.acc_grumpy-coral-opossum
  QC.Doc:
    repos:
      github.com/eosc-synergy/sqaaas-api-server find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.scaly-ecru-swan.sh
        container: qc.doc_gummy-green-macaque
      github.com/eosc-synergy/sqaaas-api-server git:
        commands:
        - /usr/bin/env sh .sqa/script.muggy-russet-mouse.sh
        container: qc.doc_fuzzy-lime-chipmunk
      github.com/eosc-synergy/sqaaas-api-server markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.snazzy-taupe-tapir.sh
        container: qc.doc_hilly-ruby-bird
  QC.Lic:
    repos:
      github.com/eosc-synergy/sqaaas-api-server licensee:
        commands:
        - /usr/bin/env sh .sqa/script.chummy-pear-buzzard.sh
        container: qc.lic_scummy-champagne-ray
  QC.Sec:
    repos:
      github.com/eosc-synergy/sqaaas-api-server bandit:
        commands:
        - /usr/bin/env sh .sqa/script.flaky-denim-falcon.sh
        container: qc.sec_sloppy-alizarin-pinscher
  QC.Sty:
    repos:
      github.com/eosc-synergy/sqaaas-api-server flake8:
        commands:
        - /usr/bin/env sh .sqa/script.chummy-cerulean-chinchilla.sh
        container: qc.sty_foggy-mauve-toad
  QC.Ver:
    repos:
      github.com/eosc-synergy/sqaaas-api-server get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-amaranth-falcon.sh
        container: qc.ver_slaphappy-burgundy-dogfish
timeout: 1800
