config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.5
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/eosc-synergy/sqaaas-api-server:
      branch: !!python/tuple
      - master
      - 23727cacc3e4f1a6f200727f3a9f7a1b2dcc5d5e
      repo: https://github.com/eosc-synergy/sqaaas-api-server
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/eosc-synergy/sqaaas-api-server git:
        commands:
        - /usr/bin/env sh .sqa/script.thirsty-cerise-impala.sh
        container: qc.acc_gamy-teal-gopher
  QC.Doc:
    repos:
      github.com/eosc-synergy/sqaaas-api-server find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.breezy-bistre-flounder.sh
        container: qc.doc_ready-magenta-kiwi
      github.com/eosc-synergy/sqaaas-api-server git:
        commands:
        - /usr/bin/env sh .sqa/script.wheezy-champagne-buzzard.sh
        container: qc.doc_squirrely-copper-zorse
      github.com/eosc-synergy/sqaaas-api-server markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.messy-pear-chinook.sh
        container: qc.doc_craggy-alizarin-chinook
  QC.Lic:
    repos:
      github.com/eosc-synergy/sqaaas-api-server licensee:
        commands:
        - /usr/bin/env sh .sqa/script.scanty-tangerine-falcon.sh
        container: qc.lic_queasy-teal-snake
  QC.Sec:
    repos:
      github.com/eosc-synergy/sqaaas-api-server bandit:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-silver-centipede.sh
        container: qc.sec_clammy-sapphire-beaver
  QC.Sty:
    repos:
      github.com/eosc-synergy/sqaaas-api-server flake8:
        commands:
        - /usr/bin/env sh .sqa/script.stealthy-cyan-cassowary.sh
        container: qc.sty_sloppy-bronze-serval
      github.com/eosc-synergy/sqaaas-api-server hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.pokey-violet-millipede.sh
        container: qc.sty_paltry-maroon-hyena
      github.com/eosc-synergy/sqaaas-api-server jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.cozy-amethyst-gerbil.sh
        container: qc.sty_paltry-teal-drever
  QC.Ver:
    repos:
      github.com/eosc-synergy/sqaaas-api-server get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.hazy-malachite-scorpion.sh
        container: qc.ver_geeky-rose-mouse
timeout: 5400
