config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.7
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/eosc-synergy/sqaaas-api-server:
      branch: master
      repo: https://github.com/eosc-synergy/sqaaas-api-server
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/eosc-synergy/sqaaas-api-server git:
        commands:
        - /usr/bin/env sh .sqa/script.stealthy-corn-ray.sh
        container: qc.acc_snappy-harlequin-chinchilla
  QC.Doc:
    repos:
      github.com/eosc-synergy/sqaaas-api-server find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.cranky-chestnut-gar.sh
        container: qc.doc_snappy-plum-emu
      github.com/eosc-synergy/sqaaas-api-server git:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-chocolate-clam.sh
        container: qc.doc_skanky-seashell-walrus
      github.com/eosc-synergy/sqaaas-api-server markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.whiny-sapphire-dolphin.sh
        container: qc.doc_zippy-periwinkle-dog
  QC.Lic:
    repos:
      github.com/eosc-synergy/sqaaas-api-server licensee:
        commands:
        - /usr/bin/env sh .sqa/script.cloudy-burgundy-zebra.sh
        container: qc.lic_wiggy-cream-dogfish
  QC.Met:
    repos:
      github.com/eosc-synergy/sqaaas-api-server cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.shaggy-amethyst-bandicoot.sh
        container: qc.met_shabby-orchid-heron
  QC.Sec:
    repos:
      github.com/eosc-synergy/sqaaas-api-server bandit:
        commands:
        - /usr/bin/env sh .sqa/script.tasty-chartreuse-dormouse.sh
        container: qc.sec_geeky-platinum-nightingale
  QC.Sty:
    repos:
      github.com/eosc-synergy/sqaaas-api-server flake8:
        commands:
        - /usr/bin/env sh .sqa/script.leaky-cornflower-turkey.sh
        container: qc.sty_fuzzy-tomato-balinese
      github.com/eosc-synergy/sqaaas-api-server hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.cozy-magnolia-spider.sh
        container: qc.sty_woolly-saffron-zebu
      github.com/eosc-synergy/sqaaas-api-server jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.messy-periwinkle-bordeaux.sh
        container: qc.sty_sleazy-seashell-tapir
  QC.Ver:
    repos:
      github.com/eosc-synergy/sqaaas-api-server get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.zippy-thistle-sheepdog.sh
        container: qc.ver_flaky-rust-snail
timeout: 5400
