config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.5
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/eosc-synergy/sqaaas-api-server:
      branch: master
      repo: https://github.com/eosc-synergy/sqaaas-api-server
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/eosc-synergy/sqaaas-api-server git:
        commands:
        - /usr/bin/env sh .sqa/script.gimpy-carmine-iguana.sh
        container: qc.acc_hilly-turquoise-serval
  QC.Doc:
    repos:
      github.com/eosc-synergy/sqaaas-api-server find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.jumpy-gold-rattlesnake.sh
        container: qc.doc_zippy-alizarin-insect
      github.com/eosc-synergy/sqaaas-api-server git:
        commands:
        - /usr/bin/env sh .sqa/script.snazzy-chestnut-centipede.sh
        container: qc.doc_whiny-lavender-zebu
      github.com/eosc-synergy/sqaaas-api-server markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-denim-chipmunk.sh
        container: qc.doc_cheeky-brass-uguisu
  QC.Lic:
    repos:
      github.com/eosc-synergy/sqaaas-api-server licensee:
        commands:
        - /usr/bin/env sh .sqa/script.snoopy-celadon-weasel.sh
        container: qc.lic_snappy-azure-rat
  QC.Sec:
    repos:
      github.com/eosc-synergy/sqaaas-api-server bandit:
        commands:
        - /usr/bin/env sh .sqa/script.goopy-razzmatazz-tzu.sh
        container: qc.sec_goopy-rust-angelfish
  QC.Sty:
    repos:
      github.com/eosc-synergy/sqaaas-api-server flake8:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-black-squid.sh
        container: qc.sty_ugly-magnolia-eel
      github.com/eosc-synergy/sqaaas-api-server hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-black-echidna.sh
        container: qc.sty_bumpy-blue-macaw
      github.com/eosc-synergy/sqaaas-api-server jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.jumpy-sapphire-dachshund.sh
        container: qc.sty_lousy-magenta-quokka
  QC.Ver:
    repos:
      github.com/eosc-synergy/sqaaas-api-server get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.trippy-teal-fossa.sh
        container: qc.ver_grumpy-green-chimpanzee
timeout: 5400
