config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-api-server:
      branch: release/2.0.0
      repo: https://github.com/EOSC-synergy/sqaaas-api-server
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: 1.6.0-alpha5
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/EOSC-synergy/sqaaas-api-server git:
        commands:
        - /usr/bin/env sh .sqa/script.gimpy-rose-ant.sh
        container: qc.acc_sleepy-firebrick-opossum
  QC.Doc:
    repos:
      github.com/EOSC-synergy/sqaaas-api-server find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-bronze-tetra.sh
        container: qc.doc_skimpy-white-hyrax
      github.com/EOSC-synergy/sqaaas-api-server markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.bluesy-lime-stingray.sh
        container: qc.doc_sloppy-cobalt-pinscher
  QC.Lic:
    repos:
      github.com/EOSC-synergy/sqaaas-api-server licensee:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-grey-loon.sh
        container: qc.lic_tasty-gamboge-chicken
  QC.Sec:
    repos:
      github.com/EOSC-synergy/sqaaas-api-server bandit:
        commands:
        - /usr/bin/env sh .sqa/script.thirsty-silver-tang.sh
        container: qc.sec_hazy-saffron-hornet
  QC.Sty:
    repos:
      github.com/EOSC-synergy/sqaaas-api-server flake8:
        commands:
        - /usr/bin/env sh .sqa/script.snoopy-celadon-newt.sh
        container: qc.sty_nippy-copper-kudu
  QC.Ver:
    repos:
      github.com/EOSC-synergy/sqaaas-api-server is_semver.py:
        commands:
        - /usr/bin/env sh .sqa/script.queasy-blue-cichlid.sh
        container: qc.ver_shaky-gold-barnacle
timeout: 600
