config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.8
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/eosc-synergy/sqaaas-api-server:
      branch: master
      repo: https://github.com/eosc-synergy/sqaaas-api-server
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/eosc-synergy/sqaaas-api-server git:
        commands:
        - /usr/bin/env sh .sqa/script.silly-wisteria-ibis.sh
        container: qc.acc_lanky-cream-crocodile
  QC.Doc:
    repos:
      github.com/eosc-synergy/sqaaas-api-server find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.hazy-wheat-kudu.sh
        container: qc.doc_silly-peach-havanese
      github.com/eosc-synergy/sqaaas-api-server git:
        commands:
        - /usr/bin/env sh .sqa/script.flaky-blue-barracuda.sh
        container: qc.doc_freaky-turquoise-woodlouse
      github.com/eosc-synergy/sqaaas-api-server markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.cozy-brass-seal.sh
        container: qc.doc_leaky-cardinal-bird
  QC.Lic:
    repos:
      github.com/eosc-synergy/sqaaas-api-server licensee:
        commands:
        - /usr/bin/env sh .sqa/script.greasy-carmine-donkey.sh
        container: qc.lic_muzzy-indigo-mist
  QC.Met:
    repos:
      github.com/eosc-synergy/sqaaas-api-server cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-tangerine-spoonbill.sh
        container: qc.met_gimpy-tomato-cichlid
  QC.Sec:
    repos:
      github.com/eosc-synergy/sqaaas-api-server bandit:
        commands:
        - /usr/bin/env sh .sqa/script.grumpy-celadon-mist.sh
        container: qc.sec_slaphappy-crimson-tang
  QC.Sty:
    repos:
      github.com/eosc-synergy/sqaaas-api-server flake8:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-cobalt-centipede.sh
        container: qc.sty_snappy-carmine-mole
      github.com/eosc-synergy/sqaaas-api-server hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.nerdy-cinnamon-pinscher.sh
        container: qc.sty_grumpy-grey-peccary
      github.com/eosc-synergy/sqaaas-api-server jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-turquoise-avocet.sh
        container: qc.sty_chummy-razzmatazz-eel
  QC.Ver:
    repos:
      github.com/eosc-synergy/sqaaas-api-server get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.flabby-burgundy-seahorse.sh
        container: qc.ver_randy-grey-foxhound
timeout: 5400
