config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: 1.6.0-alpha5
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/eosc-synergy/sqaaas-api-server:
      branch: release/2.0.0
      repo: https://github.com/eosc-synergy/sqaaas-api-server
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/eosc-synergy/sqaaas-api-server git:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-peach-tamarin.sh
        container: qc.acc_whiny-sangria-markhor
  QC.Doc:
    repos:
      github.com/eosc-synergy/sqaaas-api-server find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.scummy-scarlet-urchin.sh
        container: qc.doc_skanky-aquamarine-catfish
      github.com/eosc-synergy/sqaaas-api-server markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.leaky-buff-balinese.sh
        container: qc.doc_cozy-zucchini-hyena
  QC.Lic:
    repos:
      github.com/eosc-synergy/sqaaas-api-server licensee:
        commands:
        - /usr/bin/env sh .sqa/script.baggy-maroon-stoat.sh
        container: qc.lic_paltry-cinnabar-paradise
  QC.Sec:
    repos:
      github.com/eosc-synergy/sqaaas-api-server bandit:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-linen-abyssinian.sh
        container: qc.sec_hilly-viridian-kangaroo
  QC.Sty:
    repos:
      github.com/eosc-synergy/sqaaas-api-server flake8:
        commands:
        - /usr/bin/env sh .sqa/script.slimy-carmine-liger.sh
        container: qc.sty_randy-ivory-kingfisher
  QC.Ver:
    repos:
      github.com/eosc-synergy/sqaaas-api-server is_semver.py:
        commands:
        - /usr/bin/env sh .sqa/script.silly-chartreuse-terrier.sh
        container: qc.ver_homely-zucchini-dachsbracke
timeout: 600
