config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.4
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/eosc-synergy/sqaaas-api-server:
      branch: master
      repo: https://github.com/eosc-synergy/sqaaas-api-server
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/eosc-synergy/sqaaas-api-server git:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-platinum-ibis.sh
        container: qc.acc_flimsy-auburn-avocet
  QC.Doc:
    repos:
      github.com/eosc-synergy/sqaaas-api-server find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.thirsty-yellow-hippopotamus.sh
        container: qc.doc_pretty-scarlet-dog
      github.com/eosc-synergy/sqaaas-api-server git:
        commands:
        - /usr/bin/env sh .sqa/script.lousy-alizarin-goat.sh
        container: qc.doc_cozy-chocolate-weasel
      github.com/eosc-synergy/sqaaas-api-server markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.muggy-thistle-foxhound.sh
        container: qc.doc_nerdy-salmon-sloth
  QC.Lic:
    repos:
      github.com/eosc-synergy/sqaaas-api-server licensee:
        commands:
        - /usr/bin/env sh .sqa/script.wimpy-lemon-dolphin.sh
        container: qc.lic_shaky-xanthic-balinese
  QC.Sec:
    repos:
      github.com/eosc-synergy/sqaaas-api-server bandit:
        commands:
        - /usr/bin/env sh .sqa/script.tasty-razzmatazz-capuchin.sh
        container: qc.sec_messy-gamboge-quetzal
  QC.Sty:
    repos:
      github.com/eosc-synergy/sqaaas-api-server flake8:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-wisteria-molly.sh
        container: qc.sty_lousy-rust-jaguar
      github.com/eosc-synergy/sqaaas-api-server hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.jumpy-amaranth-dachsbracke.sh
        container: qc.sty_grumpy-wheat-crane
      github.com/eosc-synergy/sqaaas-api-server jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.blurry-red-dunker.sh
        container: qc.sty_randy-goldenrod-dingo
  QC.Ver:
    repos:
      github.com/eosc-synergy/sqaaas-api-server get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-malachite-fish.sh
        container: qc.ver_snazzy-lime-bonobo
timeout: 1800
