config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: 1.7.0_no_kubectl
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/eosc-synergy/sqaaas-api-server:
      branch: master
      repo: https://github.com/eosc-synergy/sqaaas-api-server
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/eosc-synergy/sqaaas-api-server git:
        commands:
        - /usr/bin/env sh .sqa/script.lumpy-malachite-tang.sh
        container: qc.acc_trippy-pear-stoat
  QC.Doc:
    repos:
      github.com/eosc-synergy/sqaaas-api-server find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-ochre-zebra.sh
        container: qc.doc_shaky-tomato-cheetah
      github.com/eosc-synergy/sqaaas-api-server git:
        commands:
        - /usr/bin/env sh .sqa/script.homey-mustard-angelfish.sh
        container: qc.doc_flabby-amber-abyssinian
      github.com/eosc-synergy/sqaaas-api-server markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.flabby-beige-reindeer.sh
        container: qc.doc_gimpy-aquamarine-tang
  QC.FAIR:
    repos:
      github.com/eosc-synergy/sqaaas-api-server F-UJI:
        commands:
        - /usr/bin/env sh .sqa/script.wimpy-smalt-squirrel.sh
        container: qc.fair_goopy-goldenrod-forest
  QC.Lic:
    repos:
      github.com/eosc-synergy/sqaaas-api-server licensee:
        commands:
        - /usr/bin/env sh .sqa/script.flabby-xanthic-zorse.sh
        container: qc.lic_frumpy-champagne-avocet
  QC.Sec:
    repos:
      github.com/eosc-synergy/sqaaas-api-server bandit:
        commands:
        - /usr/bin/env sh .sqa/script.stealthy-myrtle-sponge.sh
        container: qc.sec_stuffy-lilac-binturong
  QC.Sty:
    repos:
      github.com/eosc-synergy/sqaaas-api-server flake8:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-periwinkle-hamster.sh
        container: qc.sty_stinky-rust-alligator
  QC.Ver:
    repos:
      github.com/eosc-synergy/sqaaas-api-server get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.scaly-seashell-civet.sh
        container: qc.ver_paltry-thistle-terrier
timeout: 1800
