config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.5
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/eosc-synergy/sqaaas-api-server:
      branch: master
      repo: https://github.com/eosc-synergy/sqaaas-api-server
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/eosc-synergy/sqaaas-api-server git:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-plum-wildebeest.sh
        container: qc.acc_hazy-rose-crab
  QC.Doc:
    repos:
      github.com/eosc-synergy/sqaaas-api-server find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.pasty-salmon-scorpion.sh
        container: qc.doc_muzzy-carmine-crocodile
      github.com/eosc-synergy/sqaaas-api-server git:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-teal-quetzal.sh
        container: qc.doc_squirrely-lemon-kudu
      github.com/eosc-synergy/sqaaas-api-server markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.goopy-grey-butterfly.sh
        container: qc.doc_goopy-cardinal-shrew
  QC.Lic:
    repos:
      github.com/eosc-synergy/sqaaas-api-server licensee:
        commands:
        - /usr/bin/env sh .sqa/script.lousy-xanthic-mist.sh
        container: qc.lic_sleepy-aqua-earwig
  QC.Sec:
    repos:
      github.com/eosc-synergy/sqaaas-api-server bandit:
        commands:
        - /usr/bin/env sh .sqa/script.scanty-periwinkle-boar.sh
        container: qc.sec_cranky-eggplant-horse
  QC.Sty:
    repos:
      github.com/eosc-synergy/sqaaas-api-server flake8:
        commands:
        - /usr/bin/env sh .sqa/script.nerdy-cardinal-baboon.sh
        container: qc.sty_shaggy-violet-hippopotamus
      github.com/eosc-synergy/sqaaas-api-server hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.bumpy-chartreuse-angelfish.sh
        container: qc.sty_ready-smalt-lizard
      github.com/eosc-synergy/sqaaas-api-server jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.goopy-mustard-capuchin.sh
        container: qc.sty_clammy-dandelion-iguana
  QC.Ver:
    repos:
      github.com/eosc-synergy/sqaaas-api-server get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.skanky-platinum-frog.sh
        container: qc.ver_cloudy-sangria-abyssinian
timeout: 5400
