config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-api-server:
      branch: master
      repo: https://github.com/EOSC-synergy/sqaaas-api-server
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.7
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/EOSC-synergy/sqaaas-api-server git:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-bistre-bee.sh
        container: qc.acc_grumpy-bronze-capybara
  QC.Doc:
    repos:
      github.com/EOSC-synergy/sqaaas-api-server find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-maroon-quetzal.sh
        container: qc.doc_messy-tomato-whale
      github.com/EOSC-synergy/sqaaas-api-server git:
        commands:
        - /usr/bin/env sh .sqa/script.greasy-viridian-havanese.sh
        container: qc.doc_chewy-fuchsia-dolphin
      github.com/EOSC-synergy/sqaaas-api-server markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.cloudy-cardinal-bee.sh
        container: qc.doc_tacky-purple-urchin
  QC.Lic:
    repos:
      github.com/EOSC-synergy/sqaaas-api-server licensee:
        commands:
        - /usr/bin/env sh .sqa/script.scanty-xanthic-moose.sh
        container: qc.lic_slaphappy-jade-hyrax
  QC.Sec:
    repos:
      github.com/EOSC-synergy/sqaaas-api-server bandit:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-tangerine-angora.sh
        container: qc.sec_seedy-malachite-wombat
  QC.Sty:
    repos:
      github.com/EOSC-synergy/sqaaas-api-server flake8:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-rose-numbat.sh
        container: qc.sty_sunny-cornflower-fox
      github.com/EOSC-synergy/sqaaas-api-server hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.scaly-aquamarine-coati.sh
        container: qc.sty_skimpy-dandelion-scorpion
      github.com/EOSC-synergy/sqaaas-api-server jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.chummy-chocolate-cougar.sh
        container: qc.sty_sickly-persimmon-shrew
  QC.Ver:
    repos:
      github.com/EOSC-synergy/sqaaas-api-server get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-celadon-bloodhound.sh
        container: qc.ver_shaggy-jade-gecko
timeout: 1800
