config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-api-server:
      branch: master
      repo: https://github.com/EOSC-synergy/sqaaas-api-server
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.5
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/EOSC-synergy/sqaaas-api-server git:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-harlequin-goose.sh
        container: qc.acc_muzzy-myrtle-hare
  QC.Doc:
    repos:
      github.com/EOSC-synergy/sqaaas-api-server find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.gimpy-cerise-wildebeest.sh
        container: qc.doc_shabby-turquoise-beaver
      github.com/EOSC-synergy/sqaaas-api-server git:
        commands:
        - /usr/bin/env sh .sqa/script.bumpy-gold-millipede.sh
        container: qc.doc_whiny-orange-horse
      github.com/EOSC-synergy/sqaaas-api-server markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.surly-viridian-caracal.sh
        container: qc.doc_squeaky-malachite-markhor
  QC.Lic:
    repos:
      github.com/EOSC-synergy/sqaaas-api-server licensee:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-malachite-llama.sh
        container: qc.lic_queasy-cyan-fowl
  QC.Sec:
    repos:
      github.com/EOSC-synergy/sqaaas-api-server bandit:
        commands:
        - /usr/bin/env sh .sqa/script.stealthy-chestnut-saola.sh
        container: qc.sec_thirsty-turquoise-hedgehog
  QC.Sty:
    repos:
      github.com/EOSC-synergy/sqaaas-api-server flake8:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-myrtle-spaniel.sh
        container: qc.sty_wimpy-orchid-javanese
      github.com/EOSC-synergy/sqaaas-api-server hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.bluesy-pumpkin-bear.sh
        container: qc.sty_cranky-firebrick-guppy
      github.com/EOSC-synergy/sqaaas-api-server jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.chummy-lime-uguisu.sh
        container: qc.sty_ugly-cornflower-whippet
  QC.Ver:
    repos:
      github.com/EOSC-synergy/sqaaas-api-server get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-malachite-chihuahua.sh
        container: qc.ver_messy-coral-ferret
timeout: 1800
