config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.5
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/eosc-synergy/sqaaas-api-server:
      branch: master
      repo: https://github.com/eosc-synergy/sqaaas-api-server
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/eosc-synergy/sqaaas-api-server git:
        commands:
        - /usr/bin/env sh .sqa/script.gimpy-amethyst-crane.sh
        container: qc.acc_chummy-tan-grasshopper
  QC.Doc:
    repos:
      github.com/eosc-synergy/sqaaas-api-server find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.flabby-cyan-tarantula.sh
        container: qc.doc_muzzy-thistle-lemming
      github.com/eosc-synergy/sqaaas-api-server git:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-magenta-gecko.sh
        container: qc.doc_clammy-viridian-dogfish
      github.com/eosc-synergy/sqaaas-api-server markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.hazy-thistle-argentino.sh
        container: qc.doc_cheeky-thistle-camel
  QC.Lic:
    repos:
      github.com/eosc-synergy/sqaaas-api-server licensee:
        commands:
        - /usr/bin/env sh .sqa/script.flabby-chestnut-wolf.sh
        container: qc.lic_gloppy-amaranth-monster
  QC.Sec:
    repos:
      github.com/eosc-synergy/sqaaas-api-server bandit:
        commands:
        - /usr/bin/env sh .sqa/script.boozy-cerise-rabbit.sh
        container: qc.sec_sleazy-lilac-buffalo
  QC.Sty:
    repos:
      github.com/eosc-synergy/sqaaas-api-server flake8:
        commands:
        - /usr/bin/env sh .sqa/script.sickly-tangerine-javanese.sh
        container: qc.sty_sloppy-persimmon-kudu
      github.com/eosc-synergy/sqaaas-api-server hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.gloppy-grey-guppy.sh
        container: qc.sty_tasty-fuchsia-spaniel
      github.com/eosc-synergy/sqaaas-api-server jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-magenta-catfish.sh
        container: qc.sty_homey-aqua-leopard
  QC.Ver:
    repos:
      github.com/eosc-synergy/sqaaas-api-server get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.breezy-aquamarine-beetle.sh
        container: qc.ver_frumpy-ecru-sponge
timeout: 1800
