config:
  credentials:
  - id: upv_im_id
    password_var: IM_PASS
    username_var: IM_USER
  - id: incd_openstack_id
    password_var: OPENSTACK_PASS
    username_var: OPENSTACK_USER
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: 1.7.0-alpha2
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/eosc-synergy/sqaaas-api-server:
      branch: master
      repo: https://github.com/eosc-synergy/sqaaas-api-server
    github.com/eosc-synergy/sqaaas-docs:
      branch: master
      repo: https://github.com/eosc-synergy/sqaaas-docs
    github.com/orviz/IM-sqaaas-test:
      branch: master
      repo: https://github.com/orviz/IM-sqaaas-test
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/eosc-synergy/sqaaas-api-server git:
        commands:
        - /usr/bin/env sh .sqa/script.skanky-lime-tetra.sh
        container: qc.acc_shaggy-cream-horse
  QC.Doc:
    repos:
      github.com/eosc-synergy/sqaaas-docs find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.trippy-saffron-bandicoot.sh
        container: qc.doc_flaky-mauve-dragon
      github.com/eosc-synergy/sqaaas-docs git:
        commands:
        - /usr/bin/env sh .sqa/script.breezy-beige-collie.sh
        container: qc.doc_sloppy-gold-coral
      github.com/eosc-synergy/sqaaas-docs markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.shabby-heliotrope-bat.sh
        container: qc.doc_flabby-yellow-caiman
  QC.FAIR:
    repos:
      github.com/eosc-synergy/sqaaas-api-server F-UJI:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-auburn-mayfly.sh
        container: qc.fair_freaky-jade-capuchin
  QC.Lic:
    repos:
      github.com/eosc-synergy/sqaaas-api-server licensee:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-sangria-dhole.sh
        container: qc.lic_snazzy-silver-zebra
  QC.Sec:
    repos:
      github.com/eosc-synergy/sqaaas-api-server bandit:
        commands:
        - /usr/bin/env sh .sqa/script.gamy-cornflower-sponge.sh
        container: qc.sec_shaggy-goldenrod-budgerigar
  QC.Sty:
    repos:
      github.com/eosc-synergy/sqaaas-api-server flake8:
        commands:
        - /usr/bin/env sh .sqa/script.greasy-ecru-numbat.sh
        container: qc.sty_gamy-sangria-fousek
  QC.Ver:
    repos:
      github.com/eosc-synergy/sqaaas-api-server get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-ivory-moose.sh
        container: qc.ver_stuffy-champagne-emu
  SvcQC.Dep:
    repos:
      github.com/orviz/IM-sqaaas-test im_client:
        commands:
        - /usr/bin/env sh .sqa/script.jumpy-maroon-vole.sh
        container: svcqc.dep_tasty-amber-barracuda
timeout: 600
