config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.7
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/eosc-synergy/sqaaas-api-server:
      branch: master
      repo: https://github.com/eosc-synergy/sqaaas-api-server
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/eosc-synergy/sqaaas-api-server git:
        commands:
        - /usr/bin/env sh .sqa/script.skimpy-brass-devil.sh
        container: qc.acc_cozy-azure-quail
  QC.Doc:
    repos:
      github.com/eosc-synergy/sqaaas-api-server find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-harlequin-chinchilla.sh
        container: qc.doc_frumpy-heliotrope-capybara
      github.com/eosc-synergy/sqaaas-api-server git:
        commands:
        - /usr/bin/env sh .sqa/script.tacky-azure-eagle.sh
        container: qc.doc_sleepy-maroon-fox
      github.com/eosc-synergy/sqaaas-api-server markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.sleazy-bistre-tortoise.sh
        container: qc.doc_foggy-eggplant-reindeer
  QC.Lic:
    repos:
      github.com/eosc-synergy/sqaaas-api-server licensee:
        commands:
        - /usr/bin/env sh .sqa/script.cheeky-olive-dane.sh
        container: qc.lic_boozy-ivory-fossa
  QC.Sec:
    repos:
      github.com/eosc-synergy/sqaaas-api-server bandit:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-mustard-cuscus.sh
        container: qc.sec_chummy-taupe-oriole
  QC.Sty:
    repos:
      github.com/eosc-synergy/sqaaas-api-server flake8:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-malachite-dugong.sh
        container: qc.sty_snoopy-saffron-mouse
      github.com/eosc-synergy/sqaaas-api-server hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.flaky-harlequin-mongoose.sh
        container: qc.sty_messy-jade-buzzard
      github.com/eosc-synergy/sqaaas-api-server jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-periwinkle-axolotl.sh
        container: qc.sty_skimpy-taupe-cockroach
  QC.Ver:
    repos:
      github.com/eosc-synergy/sqaaas-api-server get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.grumpy-aquamarine-akita.sh
        container: qc.ver_queasy-cornflower-frigatebird
timeout: 1800
