config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/gosec
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/eosc-synergy/sqaaas-api-server:
      branch: master
      repo: https://github.com/eosc-synergy/sqaaas-api-server
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/eosc-synergy/sqaaas-api-server git:
        commands:
        - /usr/bin/env sh .sqa/script.shaggy-xanthic-bombay.sh
        container: qc.acc_smelly-gold-macaque
  QC.Doc:
    repos:
      github.com/eosc-synergy/sqaaas-api-server find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.zippy-lemon-hornet.sh
        container: qc.doc_tacky-copper-quail
      github.com/eosc-synergy/sqaaas-api-server git:
        commands:
        - /usr/bin/env sh .sqa/script.gimpy-teal-falcon.sh
        container: qc.doc_fuzzy-champagne-hedgehog
      github.com/eosc-synergy/sqaaas-api-server markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.gamy-lilac-iguana.sh
        container: qc.doc_shabby-asparagus-jellyfish
  QC.Lic:
    repos:
      github.com/eosc-synergy/sqaaas-api-server licensee:
        commands:
        - /usr/bin/env sh .sqa/script.queasy-white-bear.sh
        container: qc.lic_lanky-fuchsia-loon
  QC.Sec:
    repos:
      github.com/eosc-synergy/sqaaas-api-server bandit:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-cream-skunk.sh
        container: qc.sec_thirsty-grey-frigatebird
      github.com/eosc-synergy/sqaaas-api-server gosec:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-eggplant-whale.sh
        container: qc.sec_droopy-gamboge-zebu
  QC.Sty:
    repos:
      github.com/eosc-synergy/sqaaas-api-server flake8:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-vermilion-moorhen.sh
        container: qc.sty_freaky-lavender-fossa
  QC.Ver:
    repos:
      github.com/eosc-synergy/sqaaas-api-server get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.dorky-silver-dragon.sh
        container: qc.ver_dorky-khaki-dugong
timeout: 1800
