config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-api-server:
      branch: master
      repo: https://github.com/EOSC-synergy/sqaaas-api-server
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.5
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/EOSC-synergy/sqaaas-api-server git:
        commands:
        - /usr/bin/env sh .sqa/script.homely-silver-echidna.sh
        container: qc.acc_surly-amber-whale
  QC.Doc:
    repos:
      github.com/EOSC-synergy/sqaaas-api-server find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.shabby-taupe-squirt.sh
        container: qc.doc_hasty-ecru-dragonfly
      github.com/EOSC-synergy/sqaaas-api-server git:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-copper-frigatebird.sh
        container: qc.doc_stuffy-platinum-coral
      github.com/EOSC-synergy/sqaaas-api-server markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-khaki-chipmunk.sh
        container: qc.doc_ready-violet-goose
  QC.Lic:
    repos:
      github.com/EOSC-synergy/sqaaas-api-server licensee:
        commands:
        - /usr/bin/env sh .sqa/script.surly-lemon-chinook.sh
        container: qc.lic_wheezy-alizarin-sheepdog
  QC.Sec:
    repos:
      github.com/EOSC-synergy/sqaaas-api-server bandit:
        commands:
        - /usr/bin/env sh .sqa/script.nerdy-chocolate-chimpanzee.sh
        container: qc.sec_goopy-pear-mau
  QC.Sty:
    repos:
      github.com/EOSC-synergy/sqaaas-api-server flake8:
        commands:
        - /usr/bin/env sh .sqa/script.nerdy-green-gar.sh
        container: qc.sty_blurry-alizarin-beaver
      github.com/EOSC-synergy/sqaaas-api-server hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-charcoal-moth.sh
        container: qc.sty_wiggy-firebrick-chin
      github.com/EOSC-synergy/sqaaas-api-server jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.greasy-cerulean-ant.sh
        container: qc.sty_randy-charcoal-rottweiler
  QC.Ver:
    repos:
      github.com/EOSC-synergy/sqaaas-api-server get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.frumpy-apricot-civet.sh
        container: qc.ver_smelly-fuchsia-moose
timeout: 1800
