config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.7
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/eosc-synergy/sqaaas-api-server:
      branch: master
      repo: https://github.com/eosc-synergy/sqaaas-api-server
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/eosc-synergy/sqaaas-api-server git:
        commands:
        - /usr/bin/env sh .sqa/script.woolly-chestnut-harrier.sh
        container: qc.acc_ready-dandelion-anteater
  QC.Doc:
    repos:
      github.com/eosc-synergy/sqaaas-api-server find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-brown-chipmunk.sh
        container: qc.doc_blurry-heliotrope-llama
      github.com/eosc-synergy/sqaaas-api-server git:
        commands:
        - /usr/bin/env sh .sqa/script.bluesy-smalt-bear.sh
        container: qc.doc_gummy-burgundy-rat
      github.com/eosc-synergy/sqaaas-api-server markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.zippy-emerald-zebra.sh
        container: qc.doc_muggy-ochre-chameleon
  QC.Lic:
    repos:
      github.com/eosc-synergy/sqaaas-api-server licensee:
        commands:
        - /usr/bin/env sh .sqa/script.whiny-tan-reindeer.sh
        container: qc.lic_nerdy-amaranth-dhole
  QC.Met:
    repos:
      github.com/eosc-synergy/sqaaas-api-server cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-purple-frise.sh
        container: qc.met_stinky-goldenrod-donkey
  QC.Sec:
    repos:
      github.com/eosc-synergy/sqaaas-api-server bandit:
        commands:
        - /usr/bin/env sh .sqa/script.shaky-orchid-lemming.sh
        container: qc.sec_clammy-ultramarine-seahorse
  QC.Sty:
    repos:
      github.com/eosc-synergy/sqaaas-api-server flake8:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-ecru-manatee.sh
        container: qc.sty_gimpy-lilac-gibbon
      github.com/eosc-synergy/sqaaas-api-server hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.stealthy-heliotrope-horse.sh
        container: qc.sty_shaky-lime-bobcat
      github.com/eosc-synergy/sqaaas-api-server jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.stuffy-cream-devil.sh
        container: qc.sty_hazy-gamboge-olm
  QC.Ver:
    repos:
      github.com/eosc-synergy/sqaaas-api-server get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-goldenrod-jackal.sh
        container: qc.ver_shaggy-chestnut-catfish
timeout: 5400
