config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.7
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/eosc-synergy/sqaaas-api-server:
      branch: feature/flake8
      repo: https://github.com/eosc-synergy/sqaaas-api-server
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/eosc-synergy/sqaaas-api-server git:
        commands:
        - /usr/bin/env sh .sqa/script.chummy-cyan-molly.sh
        container: qc.acc_frumpy-aquamarine-buffalo
  QC.Doc:
    repos:
      github.com/eosc-synergy/sqaaas-api-server find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.bumpy-cardinal-spoonbill.sh
        container: qc.doc_gummy-xanthic-forest
      github.com/eosc-synergy/sqaaas-api-server git:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-magenta-chinchilla.sh
        container: qc.doc_crappy-malachite-argentino
      github.com/eosc-synergy/sqaaas-api-server markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.sickly-black-fousek.sh
        container: qc.doc_lousy-rust-snake
  QC.Lic:
    repos:
      github.com/eosc-synergy/sqaaas-api-server licensee:
        commands:
        - /usr/bin/env sh .sqa/script.gimpy-rust-forest.sh
        container: qc.lic_surly-goldenrod-coyote
  QC.Sec:
    repos:
      github.com/eosc-synergy/sqaaas-api-server bandit:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-myrtle-crocodile.sh
        container: qc.sec_paltry-white-guppy
  QC.Sty:
    repos:
      github.com/eosc-synergy/sqaaas-api-server flake8:
        commands:
        - /usr/bin/env sh .sqa/script.trippy-amethyst-cheetah.sh
        container: qc.sty_lumpy-tangerine-panda
      github.com/eosc-synergy/sqaaas-api-server hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.thirsty-charcoal-cichlid.sh
        container: qc.sty_blurry-salmon-camel
      github.com/eosc-synergy/sqaaas-api-server jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.boozy-gold-zebra.sh
        container: qc.sty_beady-flax-chameleon
  QC.Ver:
    repos:
      github.com/eosc-synergy/sqaaas-api-server get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-salmon-tang.sh
        container: qc.ver_baggy-gold-barracuda
timeout: 5400
