config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.5
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/eosc-synergy/sqaaas-api-server:
      branch: master
      repo: https://github.com/eosc-synergy/sqaaas-api-server
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/eosc-synergy/sqaaas-api-server git:
        commands:
        - /usr/bin/env sh .sqa/script.scanty-champagne-moth.sh
        container: qc.acc_lousy-chestnut-squirrel
  QC.Doc:
    repos:
      github.com/eosc-synergy/sqaaas-api-server find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-carmine-vulture.sh
        container: qc.doc_whiny-burgundy-monkey
      github.com/eosc-synergy/sqaaas-api-server git:
        commands:
        - /usr/bin/env sh .sqa/script.scanty-tangerine-wildebeest.sh
        container: qc.doc_ready-seashell-jaguar
      github.com/eosc-synergy/sqaaas-api-server markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.cranky-ivory-foxhound.sh
        container: qc.doc_woozy-mustard-quoll
  QC.Lic:
    repos:
      github.com/eosc-synergy/sqaaas-api-server licensee:
        commands:
        - /usr/bin/env sh .sqa/script.gamy-cyan-schnauzer.sh
        container: qc.lic_stinky-taupe-centipede
  QC.Sec:
    repos:
      github.com/eosc-synergy/sqaaas-api-server bandit:
        commands:
        - /usr/bin/env sh .sqa/script.dorky-heliotrope-kingfisher.sh
        container: qc.sec_randy-pumpkin-bear
  QC.Sty:
    repos:
      github.com/eosc-synergy/sqaaas-api-server flake8:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-bistre-tapir.sh
        container: qc.sty_homey-zucchini-moorhen
      github.com/eosc-synergy/sqaaas-api-server hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.ready-coral-dog.sh
        container: qc.sty_foggy-cinnabar-loon
      github.com/eosc-synergy/sqaaas-api-server jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.bluesy-seashell-nightingale.sh
        container: qc.sty_flaky-copper-beaver
  QC.Ver:
    repos:
      github.com/eosc-synergy/sqaaas-api-server get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.wimpy-thistle-flounder.sh
        container: qc.ver_gamy-maroon-dachshund
timeout: 5400
