config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.2
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/eosc-synergy/sqaaas-api-server:
      branch: master
      repo: https://github.com/eosc-synergy/sqaaas-api-server
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/eosc-synergy/sqaaas-api-server git:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-tomato-quoll.sh
        container: qc.acc_ugly-violet-elephant
  QC.Doc:
    repos:
      github.com/eosc-synergy/sqaaas-api-server find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.pokey-lemon-zonkey.sh
        container: qc.doc_randy-aquamarine-mongrel
      github.com/eosc-synergy/sqaaas-api-server git:
        commands:
        - /usr/bin/env sh .sqa/script.jumpy-periwinkle-spider.sh
        container: qc.doc_wiggy-aquamarine-jackal
      github.com/eosc-synergy/sqaaas-api-server markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.pasty-plum-monster.sh
        container: qc.doc_boozy-zucchini-macaw
  QC.Lic:
    repos:
      github.com/eosc-synergy/sqaaas-api-server licensee:
        commands:
        - /usr/bin/env sh .sqa/script.slimy-lime-dalmatian.sh
        container: qc.lic_stealthy-alizarin-setter
  QC.Sec:
    repos:
      github.com/eosc-synergy/sqaaas-api-server bandit:
        commands:
        - /usr/bin/env sh .sqa/script.flabby-rust-mist.sh
        container: qc.sec_surly-cyan-hyrax
      github.com/eosc-synergy/sqaaas-api-server gosec:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-blue-starfish.sh
        container: qc.sec_lumpy-aqua-chicken
  QC.Sty:
    repos:
      github.com/eosc-synergy/sqaaas-api-server flake8:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-ruby-bordeaux.sh
        container: qc.sty_slaphappy-brown-deer
      github.com/eosc-synergy/sqaaas-api-server staticcheck:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-teal-dormouse.sh
        container: qc.sty_bluesy-brown-frigatebird
  QC.Ver:
    repos:
      github.com/eosc-synergy/sqaaas-api-server get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.whiny-yellow-spider.sh
        container: qc.ver_muzzy-violet-urchin
timeout: 1800
