config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.5
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/eosc-synergy/sqaaas-api-server:
      branch: master
      repo: https://github.com/eosc-synergy/sqaaas-api-server
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/eosc-synergy/sqaaas-api-server git:
        commands:
        - /usr/bin/env sh .sqa/script.cheeky-seashell-kudu.sh
        container: qc.acc_smelly-malachite-bulldog
  QC.Doc:
    repos:
      github.com/eosc-synergy/sqaaas-api-server find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-magnolia-tortoise.sh
        container: qc.doc_stealthy-ecru-paradise
      github.com/eosc-synergy/sqaaas-api-server git:
        commands:
        - /usr/bin/env sh .sqa/script.clammy-red-lizard.sh
        container: qc.doc_seedy-pink-urchin
      github.com/eosc-synergy/sqaaas-api-server markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.flabby-cardinal-toucan.sh
        container: qc.doc_stuffy-flax-panda
  QC.Lic:
    repos:
      github.com/eosc-synergy/sqaaas-api-server licensee:
        commands:
        - /usr/bin/env sh .sqa/script.shaky-mauve-dane.sh
        container: qc.lic_zippy-bistre-manatee
  QC.Sec:
    repos:
      github.com/eosc-synergy/sqaaas-api-server bandit:
        commands:
        - /usr/bin/env sh .sqa/script.homely-wisteria-dodo.sh
        container: qc.sec_jumpy-pink-chihuahua
  QC.Sty:
    repos:
      github.com/eosc-synergy/sqaaas-api-server flake8:
        commands:
        - /usr/bin/env sh .sqa/script.randy-orchid-crocodile.sh
        container: qc.sty_nippy-corn-lemur
      github.com/eosc-synergy/sqaaas-api-server hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.clammy-denim-vulture.sh
        container: qc.sty_scummy-razzmatazz-bison
      github.com/eosc-synergy/sqaaas-api-server jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-wisteria-sparrow.sh
        container: qc.sty_flaky-auburn-cockroach
  QC.Ver:
    repos:
      github.com/eosc-synergy/sqaaas-api-server get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-teal-centipede.sh
        container: qc.ver_hazy-sapphire-manatee
timeout: 5400
